"""empty message

Revision ID: 11525eda6ffb
Revises: 292d0ae7ab06
Create Date: 2022-02-02 10:33:16.064867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11525eda6ffb'
down_revision = '292d0ae7ab06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film_category', sa.Column('create_dttm', sa.DateTime(), nullable=True))
    op.add_column('film_category', sa.Column('update_dttm', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film_category', 'update_dttm')
    op.drop_column('film_category', 'create_dttm')
    # ### end Alembic commands ###
