"""Film model added all fields

Revision ID: 2bb5a673297c
Revises: b53bcf5774b0
Create Date: 2022-02-01 00:19:31.627144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb5a673297c'
down_revision = 'b53bcf5774b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('title', sa.String(length=256), nullable=True))
    op.add_column('film', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('film', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('film', sa.Column('language_id', sa.Integer(), nullable=True))
    op.add_column('film', sa.Column('rental_duration', sa.String(length=256), nullable=True))
    op.add_column('film', sa.Column('rental_rate', sa.Float(), nullable=True))
    op.add_column('film', sa.Column('length', sa.String(length=256), nullable=True))
    op.add_column('film', sa.Column('replacement_cost', sa.Float(), nullable=True))
    op.add_column('film', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('film', sa.Column('special_features', sa.String(length=256), nullable=True))
    op.add_column('film', sa.Column('fulltext', sa.String(length=256), nullable=True))
    op.add_column('film', sa.Column('create_dttm', sa.String(length=256), nullable=True))
    op.add_column('film', sa.Column('update_dttm', sa.String(length=256), nullable=True))
    op.drop_column('film', 'Title')
    op.drop_column('film', 'Description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('Description', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('Title', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('film', 'update_dttm')
    op.drop_column('film', 'create_dttm')
    op.drop_column('film', 'fulltext')
    op.drop_column('film', 'special_features')
    op.drop_column('film', 'rating')
    op.drop_column('film', 'replacement_cost')
    op.drop_column('film', 'length')
    op.drop_column('film', 'rental_rate')
    op.drop_column('film', 'rental_duration')
    op.drop_column('film', 'language_id')
    op.drop_column('film', 'release_year')
    op.drop_column('film', 'description')
    op.drop_column('film', 'title')
    # ### end Alembic commands ###
