"""empty message

Revision ID: a09067559dc7
Revises: 11525eda6ffb
Create Date: 2022-02-02 10:33:48.894404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09067559dc7'
down_revision = '11525eda6ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('create_dttm', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('update_dttm', sa.DateTime(), nullable=True))
    op.add_column('film_actor', sa.Column('create_dttm', sa.DateTime(), nullable=True))
    op.add_column('film_actor', sa.Column('update_dttm', sa.DateTime(), nullable=True))
    op.add_column('language', sa.Column('create_dttm', sa.DateTime(), nullable=True))
    op.add_column('language', sa.Column('update_dttm', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language', 'update_dttm')
    op.drop_column('language', 'create_dttm')
    op.drop_column('film_actor', 'update_dttm')
    op.drop_column('film_actor', 'create_dttm')
    op.drop_column('category', 'update_dttm')
    op.drop_column('category', 'create_dttm')
    # ### end Alembic commands ###
